ProTwo/AppTwo/urls.py
from django.urls import path
from AppTwo import views

# TEMPLATE TAGGING
app_name = 'AppTwo'

urlpatterns = [
    path('help/', views.help, name="help"),
    path('relative/',views.relative,name="relative"),
    path('users/',views.users, name="users"),
    path('register/',views.register, name="register"),
    path('forms/',views.form_name_view,name="form_name"),
    path('login/',views.user_login, name="user_login")
]

ProTwo/ProTwo/urls.py
from django.contrib import admin
from django.urls import path, include
from AppTwo import views


urlpatterns = [
    #path('',views.index, name="index"),

    path('', views.index, name="index"),
    path('app_two/', include('AppTwo.urls')),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout, name="logout"),
    path('special/',views.special, name="special"),

]

ProTwo/AppTwo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ExUser(models.Model):
    first_name = models.CharField(max_length=254)
    last_name = models.CharField(max_length=254)
    email = models.EmailField(max_length=254)

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #additional
    portfolio_site = models.URLField(blank = True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank = True)

    def __self__(self):
        return self.user.username

ProTwo/AppTwo/forms.py
from django import forms
from django.core import validators
from AppTwo.models import ExUser
from django.contrib.auth.models import User
from AppTwo.models import UserProfileInfo

# creating our own custom Validation
# def check_for_z(value):
#     if value[0].lower() != 'z':
#         raise forms.ValidationError("Need to start with Z")

class FormName(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField(label='Please verify your email')
    text = forms.CharField(widget=forms.Textarea)
    # botcatcher = forms.CharField(required=False, widget=forms.HiddenInput,
    #                               validators=[validators.MaxLengthValidator(0)])

    def clean(self):
        all_clean_data = super().clean()

        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if email != vmail:
            raise forms.ValidationError("There is a mismatch in email field! please correct it.")

class UserForm(forms.ModelForm):
        password = forms.CharField(widget=forms.PasswordInput())

        class Meta:
            model = User
            fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
        class Meta:
            model = UserProfileInfo
            fields =('portfolio_site','profile_pic')

# instead we are using django builtin validator
    # def clean_botcatcher(self):
    #     botcatcher = self.cleaned_data['botcatcher']
    #     if len(botcatcher) > 0:
    #         raise form.ValidationError("Gotcha Bot!")
    #     return botcatcher
class NewUserForm(forms.ModelForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()

    class Meta:
        model = ExUser
        fields = '__all__'

ProTwo/AppTwo/views.py
from django.shortcuts import render
# from django.http import HttpResponse
from AppTwo.models import ExUser
from .forms import FormName
from .forms import NewUserForm
from .forms import UserProfileInfoForm,UserForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import login,authenticate,logout
#from .forms import UserProfileInfoForm
# Create your views here.

def index(request):
    context_dict = {'text':'hi, there','number':100}
    return render(request,'AppTwo/index.html',context_dict)

@login_required
def special(request):
    return HttpResponse('You are logged in nice!')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def relative(request):
    return render(request,'AppTwo/relative_url_templates.html')

    #return HttpResponse("<em> My Second Project </em>")

def help(request):
    help_dict = {'feed_me':'this is the help page'}
    return render(request, 'AppTwo/help.html',context=help_dict)

def register(request):

    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user


            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'AppTwo/register.html',{'user_form':user_form,'profile_form':profile_form, 'registered':registered})


# -----------------not in use--------------------------
# def users(request):
#     user_list = User.objects.order_by('first_name')
#     users_dict = {'users':user_list}
#     return render(request,'AppTwo/users.html',context=users_dict)

def users(request):
    form = NewUserForm()
    if request.method == 'POST':
        form = NewUserForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('Form Is Invalid!')
    return render(request,'AppTwo/users.html',{'form':form})

def form_name_view(request):
    form = FormName()
    if request.method == 'POST':
        form = FormName(request.POST)

        if form.is_valid():
            # Do something code goes Here
            print('Validation Succesful')
            print('Name : '+form.cleaned_data['name'])
            print('Email : '+form.cleaned_data['email'])
            print('Text :'+form.cleaned_data['text'])
    return render(request,'AppTwo/form_page.html',{'form':form})

# function for user authentication or login
def user_login(request):

    if request.method == 'POST':
        # grab the username and password
        username = request.POST.get('username')
        password = request.POST.get('password')
        # using the built-in function for the authentication
        user = authenticate(request,username=username,password=password)

        #check wheter the user is active or not
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account Not Active')
        else:
            print('Someone tried to login and failed')
            print('Username {} and Password {}'.format(username,password))
            return HttpResponse('Invalid Username or Password is Supplied!')
    else:
        return render(request,'AppTwo/login.html')

ProTwo/templates/AppTwo/base_template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="{% url 'index' %}">Brand</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'AppTwo:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'AppTwo:help' %}">Help</a>
          </li>

          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'AppTwo:user_login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
      <div class="container">
        {% block body_block %}
        <!-- everything outside this will be inherited -->

        {% endblock %}

      </div>

  </body>
</html>

ProTwo/templates/AppTwo/form_page.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  </head>
  <body>
    <div class="container">
      <h1>Please Fill Out the Form:-</h1>
      <form  method="post">
        {% csrf_token %}
            {{ form.as_p}}
        <input type="submit" class= 'btn btn-primary'value="Submit">

      </form>
    </div>

  </body>
</html>

ProTwo/templates/AppTwo/help.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static "css/myfile.css" %}">
    <title>Injection media files</title>
  </head>
  <body>
    <h1>This is the Picture Incoming C.E.O</h1>
    <img src="{% static "images/mypic.jpg" %}" alt="ah - Oh didn't get that!">
    {{ feed_me }}

  </body>
</html>

ProTwo/templates/AppTwo/index.html
<!DOCTYPE html>
{% extends "AppTwo/base_template.html" %}
{% block body_block %}
      <div class="jumbotron">
        <h1>Welcome!</h1>
        <h2>Go to /users to see the list of user Information!</h2>
        <h2>{{ text|cut:"there" }}</h2>
        <h2>{{ number|add:"28" }}</h2>
      </div>
{% endblock %}

ProTwo/templates/AppTwo/login.html
<!DOCTYPE html>
{% extends 'AppTwo/base_template.html' %}
{% block body_block %}

<div class="jumbotron">
  <form action="{% url 'AppTwo:user_login' %}" method="POST">
    {% csrf_token %}
    <label for="username">USERNAME: </label>
    <input type="text" name="username" placeholder="Enter Username">
    <label for="password">PASSWORD:</label>
    <input type="password" name="password">
    <input type="submit" value="Login">
  </form>
</div>

{% endblock %}

ProTwo/templates/AppTwo/register.html
<!DOCTYPE html>
{% extends "AppTwo/base_template.html" %}

{% block body_block %}

  <div class="jumbotron">
    {% if registered %}
    <h1>Thank You for Registering</h1>

    {% else %}
      <h1>Register Here:</h1>
      <h3>Please fill out the form: </h3>

      <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" class="btn btn-primary" value="Register">
      </form>
    {% endif %}

  </div>
{% endblock %}

ProTwo/templates/AppTwo/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to Relative URL Templates</h1>
    <a href="{% url 'AppTwo:help' %}">The help page.</a>
    <a href="{% url 'admin:index' %}">Link to Admin</a>
    <a href="{% url 'index' %}">link to index</a>

  </body>
</html>

ProTwo/templates/AppTwo/users.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <title></title>
  </head>
  <body>
    
    <div class="container">
      <h2>Sign Up here</h2>
      <form  method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="SignUp">
      </form>

    </div>
    <!-- {% if users %}
    <h1>Here are your Users:</h1>
    <ol>
      {% for user in users %}
      <li>Users Info:</li>
        <ul style="list-style-type:circle">
          <li>First Name : {{ user.first_name }}</li>
          <li>Last Name : {{ user.last_name }}</li>
          <li>Email : {{ user.email }}</li>
        </ul>
      {% endfor %}
    </ol>
    {% else %}
    <h2>No Users Found!</h2>
    {% endif %} -->

  </body>
</html>